# real webhook trigger testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccit-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ccit-app
  template:
    metadata:
      labels:
        app: ccit-app
    spec:
      containers:
        - name: cont-1
          image: learncloudcomputing/ccitrepo:v1
          ports:
            - containerPort: 80
